const ErrorCodes = Object.freeze({
  INVALID_AMOUNT: "INVALID_AMOUNT",
  NOT_FOUND: "NOT_FOUND",
  INSUFFICIENT_FUNDS: "INSUFFICIENT_FUNDS",
  LIMIT_EXCEEDED: "LIMIT_EXCEEDED",
  ACCOUNT_FROZEN: "ACCOUNT_FROZEN",
  ACCOUNT_CLOSED: "ACCOUNT_CLOSED",
  INVALID_STATUS: "INVALID_STATUS",
  ALREADY_EXISTS: "ALREADY_EXISTS",
  ALREADY_PROCESSED: "ALREADY_PROCESSED",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  SCHEMA_ERROR: "SCHEMA_ERROR",
});

module.exports = { ErrorCodes };

